# Generated by Django 5.2.8 on 2025-12-08 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0006_alter_workpermit_status'),
        ('users', '0002_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bin',
            field=models.CharField(blank=True, default='950540000524', help_text='Заполняется, если сотрудник использует ЭЦП юридического лица', max_length=12, null=True, verbose_name='БИН Организации'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, default='АО Каражанбасмунай', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='permits.department', verbose_name='Департамент'),
        ),
    ]
