# Generated by Django 5.2.8 on 2025-12-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bin_user_company_name_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('AUDITOR', 'Аудитор'), ('ISSUER', 'Выдающий наряд'), ('WORK_PRODUCER', 'Производитель работ'), ('ADMITTING', 'Допускающий')], default='WORK_PRODUCER', max_length=20, verbose_name='Роль'),
        ),
    ]
