# Generated by Django 5.2.8 on 2025-12-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, default='АО Каражанбасмунай', max_length=50, null=True, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('AUDITOR', 'Аудитор'), ('ISSUER', 'Выдающий наряд'), ('WORK_PRODUCER', 'Производитель работ'), ('ADMITTING', 'Допускающий'), ('COORDINATOR', 'Согласующий')], default='WORK_PRODUCER', max_length=20, verbose_name='Роль'),
        ),
    ]
