# Generated by Django 5.2.8 on 2026-01-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_company_name_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('AUDITOR', 'Аудитор'), ('ISSUER', 'Выдающий наряд'), ('WORK_PRODUCER', 'Производитель работ'), ('ADMITTING', 'Допускающий'), ('COORDINATOR', 'Согласующий'), ('RESPONSIBLE', 'Ответс. руководитель работ')], default='WORK_PRODUCER', max_length=20, verbose_name='Роль'),
        ),
    ]
