# Generated by Django 5.2.8 on 2026-06-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_surname_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bin',
            field=models.CharField(blank=True, default='000000000000', help_text='Заполняется, если сотрудник использует ЭЦП юридического лица', max_length=12, null=True, verbose_name='БИН Организации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, default='ТОО Каспий Битум', max_length=50, null=True, verbose_name='Компания'),
        ),
    ]
