# Generated by Django 5.2.8 on 2025-11-24 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PENDING_APPROVAL', 'Ожидает согласования'), ('APPROVED', 'Согласован'), ('REJECTED', 'Отклонен'), ('CLOSED', 'Закрыт')], default='DRAFT', max_length=20, verbose_name='Статус наряда')),
                ('permit_id', models.CharField(max_length=50, unique=True, verbose_name='Номер наряда')),
                ('data', models.JSONField(default=dict, verbose_name='Данные формы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_permits', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.workpermittemplate', verbose_name='Тип наряда')),
            ],
            options={
                'verbose_name': 'Наряд Допуск',
                'verbose_name_plural': 'Наряды Допуска',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveSmallIntegerField(verbose_name='Порядок шага')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает подписи'), ('SIGNED', 'Подписан'), ('REJECTED', 'Отклонен')], default='PENDING', max_length=10, verbose_name='Статус шага')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подписания')),
                ('signature_data', models.TextField(blank=True, verbose_name='Данные ЭЦП')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Согласующий')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='permits.workpermit')),
            ],
            options={
                'verbose_name': 'Шаг согласования',
                'verbose_name_plural': 'Шаги согласования',
                'ordering': ('step_order',),
                'unique_together': {('permit', 'step_order')},
            },
        ),
    ]
