# Generated by Django 5.2.8 on 2025-11-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0003_dangerousworktype_department_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=17, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=17, null=True, verbose_name='Долгота'),
        ),
    ]
