# Generated by Django 5.2.8 on 2025-11-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0004_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpermit',
            name='dangerous_works',
            field=models.ManyToManyField(blank=True, to='permits.dangerousworktype', verbose_name='Виды опасных работ'),
        ),
    ]
