# Generated by Django 5.2.8 on 2025-11-25 14:53

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0005_workpermit_dangerous_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpermit',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Черновик'), ('PENDING_APPROVAL', 'Ожидает согласования'), ('APPROVED', 'Согласован'), ('REJECTED', 'Отклонен'), ('CLOSED', 'Закрыт')], default='DRAFT', max_length=20, protected=True, verbose_name='Статус наряда'),
        ),
    ]
