# Generated by Django 5.2.8 on 2025-12-28 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0006_alter_workpermit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpermit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='permits.location', verbose_name='Место работ'),
        ),
        migrations.AddField(
            model_name='workpermit',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало работ'),
        ),
        migrations.AddField(
            model_name='workpermit',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание работ'),
        ),
    ]
