# Generated by Django 5.2.8 on 2026-01-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0007_workpermit_location_workpermit_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='signed_xml',
            field=models.TextField(blank=True, null=True, verbose_name='Цифровая подпись (CMS/XML)'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='signature_data',
            field=models.TextField(blank=True, help_text='ФИО, ИИН, БИН из сертификата для быстрого просмотра', null=True, verbose_name='Данные ЭЦП'),
        ),
    ]
