# Generated by Django 5.2.8 on 2026-01-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0008_approvalstep_signed_xml_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalstep',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Ожидает очереди'), ('PENDING', 'Ожидает подписи'), ('APPROVED', 'Подписан'), ('REJECTED', 'Отклонен')], default='PENDING', max_length=10, verbose_name='Статус шага'),
        ),
    ]
