# Generated by Django 5.2.8 on 2026-01-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0009_alter_approvalstep_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='role',
            field=models.CharField(choices=[('ISSUER', 'Выдающий наряд'), ('RESPONSIBLE', 'Ответственный руководитель'), ('ADMITTING', 'Допускающий'), ('WORK_PRODUCER', 'Производитель работ'), ('COORDINATOR', 'Согласующий')], default='ISSUER', max_length=20, verbose_name='Роль согласующего'),
        ),
    ]
