# Generated by Django 5.2.8 on 2026-01-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0011_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalstep',
            name='signature_data',
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='signer_details',
            field=models.JSONField(blank=True, default=dict, help_text='ФИО, ИИН, БИН из сертификата для быстрого просмотра', verbose_name='Детали подписанта'),
        ),
    ]
