# Generated by Django 5.2.8 on 2026-01-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0012_remove_approvalstep_signature_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
    ]
