# Generated by Django 5.2.8 on 2026-02-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0013_approvalstep_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpermit',
            name='scan_file',
            field=models.FileField(blank=True, null=True, upload_to='permits_scans/%Y/%m/', verbose_name='Скан закрытого наряда'),
        ),
    ]
