# Generated by Django 5.2.8 on 2026-02-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0014_workpermit_scan_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpermit',
            name='scan_file',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/', verbose_name='Скан закрытого наряда'),
        ),
    ]
