# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0014_workpermit_scan_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpermit',
            name='safety_document',
            field=models.FileField(blank=True, null=True, upload_to='safety_docs/%Y/%m/', verbose_name='Документ к мерам безопасности'),
        ),
    ]
