# Generated by Django 5.2.8 on 2026-02-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0015_alter_workpermit_scan_file'),
        ('permits', '0015_workpermit_safety_document'),
    ]

    operations = [
    ]
