# Generated by Django 5.2.8 on 2026-04-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0016_alter_approvalstep_approver_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpermit',
            name='scan_file',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/', verbose_name='Скан закрытого наряда'),
        ),
    ]
