# Generated by Django 5.2.8 on 2026-04-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0016_merge_20260219_1249'),
        ('permits', '0017_alter_workpermit_scan_file'),
    ]

    operations = [
    ]
