# Generated by Django 5.2.8 on 2026-04-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0018_merge_20260406_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpermit',
            name='producer_closed',
            field=models.BooleanField(default=False, verbose_name='Производитель подтвердил закрытие'),
        ),
    ]
