# Generated by Django 5.2.8 on 2026-04-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0020_add_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpermit',
            name='permit_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер наряда'),
        ),
    ]
