# Generated by Django 5.2.8 on 2026-05-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0021_permit_id_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangerousworktype',
            name='name_kk',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Атауы (қазақша)'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_kk',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Атауы (қазақша)'),
        ),
    ]
