# Generated by Django 5.2.8 on 2026-05-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0022_add_name_kk_to_department_and_worktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dangerousworktype',
            name='name',
            field=models.CharField(max_length=512, unique=True, verbose_name='Вид опасных работ'),
        ),
        migrations.AlterField(
            model_name='dangerousworktype',
            name='name_kk',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Атауы (қазақша)'),
        ),
    ]
