# Generated by Django 5.2.8 on 2026-05-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0024_populate_name_kk'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpermit',
            name='loto_photo',
            field=models.FileField(blank=True, null=True, upload_to='loto_photos/%Y/%m/', verbose_name='Фото/схема LOTO'),
        ),
    ]
