# Generated by Django 5.2.8 on 2026-09-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0025_add_loto_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalWorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True, verbose_name='Вид электрических работ')),
                ('name_kk', models.CharField(blank=True, default='', max_length=512, verbose_name='Атауы (қазақша)')),
                ('color_code', models.CharField(default='#FF0000', max_length=7, verbose_name='Цвет рамки (HEX)')),
            ],
            options={
                'verbose_name': 'Вид электрических работ',
                'verbose_name_plural': 'Виды электрических работ',
            },
        ),
    ]
